### ISSUE TITLE
the provided codes cannot run

### ISSUE THREAD

**Issue by yaokl-nju** [inyeoplee77/SAGPool#1]
Hi inyeoplee77,
  Thank you for releasing your codes. I try to run your codes directly, but there are some issues. I want to know whether the released code can run on your own computer?

**Comment by inyeoplee77** [comment]
Hello klyao,
Thank you for paying attention to my project. I haven't tested on other devices yet, but I just cloned my repository and run main.py and it worked (Python 3.6.8 |Anaconda custom (64-bit), macOS 10.14.5). Is the issue related to python packages?

**Comment by yaokl-nju** [comment]
Hi inyeoplee77,
Thank you for your reply! My running environment are Python 3.6.1，Anaconda 3-4.4.0，ubuntu 16.04. The problem is related to torch_geometric library. If you can run on the your computer, it may be the implementation problem of torch_geometric library.

**Comment by yaokl-nju** [comment]
Hi, I want to know what versions are your torch_geometric, torch_scatter, torch_cluster, torch_sparse?

**Comment by yaokl-nju** [comment]
Thank god! I successfully run your code! There are some bug in the recent implementation of torch_geometric......

**Comment by Hanchen-Wang** [comment]
> Thank god! I successfully run your code! There are some bug in the recent implementation of torch_geometric......

Hi @klyao,

I think I met the same problem. 
Could you please provide the version of  torch_geometric, torch_scatter, torch_cluster, torch_sparse?
Thanks!
