### ISSUE TITLE
Optimal Hyperparameters for achieving the results as mentioned in the paper

### ISSUE THREAD

**Issue by ekagra-ranjan** [inyeoplee77/SAGPool#2]
Hi!

I read your paper on Self-Attention Pooling and found the approach and results quite amazing. I was looking forward to your code and was trying to implement them on my own. Although you have been generous enough to provide the range of hyperparameters to search on in the paper, it is still a quite extensive benchmarking which requires a good amount of compute. Not everyone can afford to do that infer the optimal hyperparameters from the range itself. It would be helpful if you can release the optimal hyperparameters for the SAGPool models so that others can also run them. :)

**Comment by inyeoplee77** [comment]
Hello,

I'm sorry for the late reply and thank you for your interest in our work.
I just made a google sheet that contains the experiment results as well as hyperparameters.

https://docs.google.com/spreadsheets/d/1JXGNOCQkRHDCQqNarteYpEuWnkNzNq_WFiQrIY276i0/edit?usp=sharing

For one thing, the code we used for the experiments was too messy, so this version is different from the code we actually used for the experiments. I validated on some of the datasets, but not all. I'm working on it, and if there is something wrong with this code, I'll fix it and update.

Thank you.
