### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mat2'

### ISSUE THREAD

**Issue by CFF-Dream** [inyeoplee77/SAGPool#3]
Hello,
when i run the main.py(SAGPool), raise the "RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'mat2'", i search for this command ,someone said the data type should be torch.cuda.FloatTensor, so i add .cuda() behind the data ,but i still doesn't work. Do u know how to deal with it.
Thank you

**Comment by CFF-Dream** [comment]
i got it!  just add '.to(args.device)' behind the 'Net(args)' at line 97

**Comment by inyeoplee77** [comment]
Sorry for late reply, and thank you! I'll update it
